server:
  port: 1003

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://ep-jolly-lab-az27jf1l-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_kOiC2Jj1cZmK
#  jpa:
#    hibernate:
#      ddl-auto: update
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
    registry-fetch-interval-seconds: 5

  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10


logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

keycloak:
  server-url: http://localhost:8080
  admin-realm: master
  realm: master
  client-id: admin-cli
  username: admin
  password: admin