server:
  port: 1002

spring:
  datasource:
    url: jdbc:postgresql://ep-jolly-lab-az27jf1l-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_kOiC2Jj1cZmK

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka

keycloak:
  server-url: http://localhost:8080
  admin-realm: master
  realm: master
  client-id: admin-cli
  username: admin
  password: admin
