spring:
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: https://keycloak-production-85d0.up.railway.app/realms/myrealm

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:1111/eureka}
  