version: "3.9"

services:
  keycloak:
    build: .

    container_name: keycloak

    ports:
      - "8080:8080"

    environment:
      KEYCLOAK_ADMIN: admin1
      KEYCLOAK_ADMIN_PASSWORD: admin1

      KC_DB: dev-file

    volumes:
      - keycloak-data:/opt/keycloak/data

    restart: unless-stopped

volumes:
  keycloak-data:
