spring:
  application:
    name: auth-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/myrealm
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8088/realms/myrealm/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: myclient
            scope: openid,profile,email
            authorization-grant-type: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true

keycloak:
  admin:
    server-url: http://localhost:8088
    admin-realm: master          # realm quản trị (mặc định)
    realm: myrealm               # realm cần tạo user
    username: admin              # admin username
    password: admin              # admin password

server:
  port: 1005