spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-production-85d0.up.railway.app/realms/myrealm

eureka:
  client:
    service-url:
      defaultZone: http://eureka:1111/eureka