server:
  port: 1004

spring:
  application:
    name: learning-service
  datasource:
    url: jdbc:postgresql://ep-late-math-az6048dt-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_lsA4k2JozKCt
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka

logging:
  level:
    org.springframework.web: DEBUG